apiVersion: apps/v1
kind: Deployment
metadata:
  name: Backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Backend
  template:
    metadata:
      labels:
        app: Backend
    spec:
      containers:
      - name: frontend-container
        image: staging/e-commerce-server:latest
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - backend

